name: Markdown Link Check
on:
  pull_request:
    branches: ["master", "main", "develop"]
jobs:
  chofer-linters:
    name: "code linting"
    uses: Toyota-Motor-North-America/chofer-actions/.github/workflows/chofer-linters.yml@feature/CDX-9780-markdown-link-check-action
    with:
      ENABLE_LINTERS: 'MARKDOWN_MARKDOWN_LINK_CHECK'
    secrets: inherit
