name: Markdown Link Check
on:
  # pull_request:
  #   branches: ["master", "main", "develop"]

  push:

jobs:
  chofer-linters:
    name: "code linting"
    uses: ./.github/workflows/linters.yml
    with:
      ENABLE_LINTERS: 'MARKDOWN_MARKDOWN_LINK_CHECK'
    secrets: inherit
