name: chofer-linters
on:
  push:
    inputs:
      ENABLE_LINTERS: #Input to decide which linter needs to be run
        description: "Comma Separated List of Linters.If ENABLE_LINTERS is set, only listed linters will be processed."
        required: false
        type: string
        default: "None"
jobs:
  chofer-linters:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    name: chofer-linters
    steps:
      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: Generate a token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a
        with:
          app_id: ${{ secrets.REGRESSION_APP_ID }}
          private_key: ${{ secrets.REGRESSION_APP_KEY }}

      - name: Checkout the chofer-action repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          repository: Toyota-Motor-North-America/chofer-actions
          ref: main
          path: ./__CHOFER_ACTIONS__
          token: ${{ steps.generate_token.outputs.token }}
          fetch-depth: 1

      - uses: ./__CHOFER_ACTIONS__/actions/prepare/linters
        with:
          ENABLE_LINTERS: ${{ inputs.ENABLE_LINTERS }}
        id: chofer-linters
