name: Run MegaLinter (markdown-link-check only)

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install MegaLinter
        uses: oxsecurity/megalinter@v7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_LINTERS: MARKDOWN_MARKDOWN_LINK_CHECK

      - name: Run MegaLinter
        run: megalinter --ci
